### PR TITLE
feat(cli): add optional flag to skip ui generation for `link-type`, `entry-type` and `collection`

### LINKED ISSUE #186: Option to exclude generating UI code
Really happy to see this repo being active improved! @c12i 

Wanted to share a want I've had for a while: I'd like an option to *not* generate any UI code for the commands `link-type`, `entry-type`, `collection`

### PR DESCRIPTION
**Pull request by c12i**
This adds an optional flag `--no-ui` for the `link-type`, `entry-type` and `collection` commands. This flag skips `ui` generation, though the `tests` folder will still be populated with generated code

This change is non intrusive and does not break the normal behaviour of these commands

closes #186

### CODE REVIEW

**Review by mattyg — APPROVED** [review]
Just flagging that if a user does *not* generate UI for an entry type, but then *does* generate UI for collection, the collection component will be trying to import an entry type component that is missing.

Not sure what the right solution to this, or if it even matters. This works great for my needs! Thank you!

**Comment by c12i** [comment]
@mattyg thanks for pointing this out, I think it matters, since we want to generate code that runs on the first try

I may have a solution for this case, having a `file_exists` custom handlebars helper to check if a file exists in the file tree before rendering any references to it. This way the references to code that was not generated will not be shown

**Comment by c12i** [comment]
added some accommodation for potentially non existent files that could be referenced @mattyg, feel free to re-review

**Review by mattyg — APPROVED** [review]
nice! good approach

**Pull request merged**
