### PR TITLE
bump version to 0.1.12

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by ThetaSinner** [comment]
@robbiecarlton Is there any context for this one? Should it be merged?

**Comment by ThetaSinner** [comment]
This seems like a sensible thing to merge with the next lot of pack-ports so I'm going to go ahead and merge it now

**Comment by ThetaSinner** [comment]
Bumped the `flake.lock` to get a newer Rust version and fix the build

**Review by ThetaSinner — APPROVED** [review]

**Comment by c12i** [comment]
@ThetaSinner should this be merged? I see that the current version on develop-0.1 is still `0.1.10`?

**Comment by c12i** [comment]
Closing in favour of a newer PR to bump the version

**Pull request closed without merging**
