### PR TITLE
chore(0.3): Update holochain client version and usage

### PR DESCRIPTION
**Pull request by c12i**

### CODE REVIEW

**Comment by c12i** [comment]
@mattyg not sure if I am missing something with the update to `AppAgentWebsocket.connect` API, but I get this error when attempting to connect via `tryorama`: `Unable to connect to Admin Websocket: No url provided and not in a Launcher environment.`

Could updating `tryorama` to use the new `AppAgentWebsocket.connect` API solve this.

**Comment by c12i** [comment]
cc @jost-s

**Comment by jost-s** [comment]
Yes, that should be it.

**Comment by jost-s** [comment]
@c12i There's a new release of Tryorama for 0.3 and 0.2 available now. Please try them and let me know.

**Comment by c12i** [comment]
Thanks @jost-s fixed the issue, CI failing due to breaking changes from holochain `0.3.0-beta-dev.38` which are getting fixed with #228

**Comment by c12i** [comment]
all good

**Review by matthme — APPROVED** [review]
Looks good to me.

**Pull request merged**
