### PR TITLE
enhancement: improve ci runtime

### PR DESCRIPTION
**Pull request by c12i**
This PR looks to improve CI runtime by parallelizing jobs via matrix in the github actions as suggested in #96, with modularization of the `run-tests.sh` script to support this change

CI runtime is reduced from 51-53 minutes to 33-35 minutes

### CODE REVIEW

**Comment by c12i** [comment]
Stuck on the `Expected` check, guessing this should be configured in the repo settings

**Review by ThetaSinner — APPROVED** [review]
Nice refactor, and great speedup!

**Comment by c12i** [comment]
@guillemcordoba do you by any chance have the capabilities to update the `required` CI pipelines for this repo?

**Comment by guillemcordoba** [comment]
@c12i I just changed your role to admin, so I think you should be able to edit whatever needs editing! Let me know if it still doesn't work.

**Comment by c12i** [comment]
Thanks @guillemcordoba, found the settings I was looking for

**Pull request merged**
