### PR TITLE
fix: limit examples to non vanilla ui frameworks

### PR DESCRIPTION
**Pull request by c12i**

### CODE REVIEW

**Comment by pdaoust** [comment]
curious: what is the driver behind this change? seems like a UX thing that someone has asked for?

**Comment by c12i** [comment]
The `vanilla` option would produce an error when the user selects it when scaffolding a forum example, so it makes sense to just omit it altogether

**Comment by matthme** [comment]
I completely missed this PR, sorry. Does it mean that the hello-world example is not available in vanilla anymore?

**Comment by c12i** [comment]
Hello world is only available in vanilla, forum only limited to the other templates, but not vanilla

**Comment by matthme** [comment]
Alright, that sounds totally reasonable, just wanted to make sure that hello-world is available in vanilla. Making more complex applications in vanilla seems like quite a cumbersome endeavor anyway without much added value I think.

**Pull request merged**
