### PR TITLE
chore: remove unused dependencies

### PR DESCRIPTION
**Pull request by c12i**
This PR removes unused dependencies detected after running `cargo +nightly udeps --all-targets`

### CODE REVIEW

**Review by matthme — APPROVED** [review]
Out of curiosity, has `degit` been ceased to be depended upon as of the `nixify` PR? I didn't even notice that this got merged in the meantime.

**Comment by c12i** [comment]
Yea, after `nixify` was merged, `degit` is no longer used. With this change, the templates are no longer downloaded via `degit`, using a nix wrapper to scaffold a web app with a custom template is now preferred.

**Comment by matthme** [comment]
Are there any instructions somewhere on how to use the templates in this new way?

**Comment by c12i** [comment]
Yes there are, the instructions are in the cargo docs on the develop branch

**Comment by matthme** [comment]
Okay great. At some point it might be nice to have a pointer to instructions in the `--help` command but since their not published on docs.rs yet I guess that needs to wait anyway.

**Pull request merged**
